### ISSUE TITLE
Receiving value just once

### ISSUE THREAD

**Issue by thomasvanta** [keijiro/OscKlak#1]
Hi!
Great work with Unity, big fan of yours here. :)
There's a tiny problem I'm having at least on Mac.
If the OSCMonitor is opened, everything works fine. The moment I close it, then I just get once more the value sent and stop receiving after that.
The issue is also shared with OSCjack.
Am I missing adding a 'master' script somewhere? In the example scenes is the same.
Thanks

**Comment by zosopro** [comment]
Hi there,

I'm also having the same problem. (in the middle of a project!)
trying to working out...

I'll appreciate your possible response....

Note : I can use the OSCjack package.

**Comment by keijiro** [comment]
Thank you for reporting. I fixed this issue! Please try it out again with the latest version :smiley:
