### ISSUE TITLE
Smartphone interaction with osc

### ISSUE THREAD

**Issue by rayNymous** [keijiro/OscKlak#3]
hi. i seen that you iteract OSC server with smartphone. can u show us project for mobile, as exemple of osc communication?

**Comment by keijiro** [comment]
I used TouchOSC.

https://hexler.net/software/touchosc

For futher details of TouchOSC, please see the TouchOSC manual.

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.
