### ISSUE TITLE
Translate on more axis

### ISSUE THREAD

**Issue by simplo** [keijiro/OscKlak#4]
Hi Kwijiri and, first of all, thank you for your wonderful work.
I have a little issue using your teapot example: I cannot underdstand how to act on both 3 axis to translate the teapot.
I tried to send x, y and z coordinates on three different OSC indexes and to use three different OSC inputs and to merge them on a single transform, or in three diffrent transform… or even to use a single OSC index with three values…
I tried, just for testing, to use three noise, instead the OSC inputs, but still I cannot translate the object on more than one axis.
Can you please help me understand which is the correct way to reach my goal?
Thank you and, please, forgive my bad english.

**Comment by keijiro** [comment]
There are some approaches for it, but the easiest one is using a hierarchy. Create empty game objects for each axis, then build a hierarchy with them as follows:

![](https://i.imgur.com/BDzldCA.png)

Now you can move each axis with a corresponding OSC input.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
